# Generated by Django 3.0 on 2020-01-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='body',
        ),
    ]
